/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"
#include <stdio.h>
#include <Helper/logger.h>
#include "Delay.h"
#include "port.h"
#include "DIO.h"
#include "usbd_framework.h"

static void int_task();

int main(void)
{
	int_task();
	log_info("Hello My name is %s \n","Mohamed Sharaf");
	Dio_WriteChannel(DIO_GREEN_LED,STD_HIGH);

  while (1)
  {
  }

}

static void int_task()
{
	// Initialize GPIO pins
	Port_Init(&portConfig);
	Delay_Init();
	usbd_initialization();
}
